### ISSUE TITLE
PhyExporter: unexpected keyword argument 'nPC'

### ISSUE THREAD

**Issue by rogerhurwitz** [SpikeInterface/spikely#58]
When I add PhyExporter to the end of a pipeline it fails with this traceback:
```
Traceback (most recent call last):
  File "/home/rogerhurwitz/miniconda3/envs/spikely/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/rogerhurwitz/miniconda3/envs/spikely/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rogerhurwitz/miniconda3/envs/spikely/lib/python3.7/site-packages/spikely-0.5.2-py3.7.egg/spikely/pipeline_model.py", line 83, in async_run
    payload = elem.run(payload, next_elem)
  File "/home/rogerhurwitz/miniconda3/envs/spikely/lib/python3.7/site-packages/spikely-0.5.2-py3.7.egg/spikely/elements/exporter.py", line 79, in run
    self.spif_class.write_sorting(**params_dict)
TypeError: write_sorting() got an unexpected keyword argument 'nPC'
```

**Comment by colehurwitz** [comment]
Looks like you need to update spiketoolkit, make sure spikely is updated, and make sure you aren’t using an old pipeline. nPC was removed from export to phy recently.

**Comment by colehurwitz** [comment]
This should go away when everything is updated
