### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by benkiisma** [SpikeInterface/spikely#77]
Hello ! 
When I try to select a sorter, spikely crashes and output this error:
```
Traceback (most recent call last):
  File "/Users/ismail/opt/anaconda3/envs/si090/lib/python3.8/site-packages/spikely/pipeline_view.py", line 63, in _elem_cbx_changed
    for spif_cls in element_cls.get_installed_spif_cls_list():
  File "/Users/ismail/opt/anaconda3/envs/si090/lib/python3.8/site-packages/spikely/elements/sorter.py", line 13, in get_installed_spif_cls_list
    raw_list = ss.installed_sorter_list
AttributeError: module 'spikesorters' has no attribute 'installed_sorter_list'
zsh: abort      spikely
(si090) ismail@MacBook-Pro-de-Ismail ~ % spikely
Traceback (most recent call last):
  File "/Users/ismail/opt/anaconda3/envs/si090/lib/python3.8/site-packages/spikely/pipeline_view.py", line 63, in _elem_cbx_changed
    for spif_cls in element_cls.get_installed_spif_cls_list():
  File "/Users/ismail/opt/anaconda3/envs/si090/lib/python3.8/site-packages/spikely/elements/sorter.py", line 13, in get_installed_spif_cls_list
    raw_list = ss.installed_sorter_list
AttributeError: module 'spikesorters' has no attribute 'installed_sorter_list'
zsh: abort      spikely
```
Can you help me find where is the problem ?

Thank you

**Comment by soucyjr** [comment]
I have a similar error :(

Have you determined a fix?

```
Traceback (most recent call last):
  File "C:\Users\Soucy\anaconda3\Lib\site-packages\spikely\pipeline_view.py", line 63, in _elem_cbx_changed
    for spif_cls in element_cls.get_installed_spif_cls_list():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soucy\anaconda3\Lib\site-packages\spikely\elements\sorter.py", line 13, in get_installed_spif_cls_list
    raw_list = ss.installed_sorter_list
               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'spikesorters' has no attribute 'installed_sorter_list'. Did you mean: 'installed_sorters'?

(spike) C:\Users\Soucy\Desktop\maxlab>installed_sorters
'installed_sorters' is not recognized as an internal or external command,
operable program or batch file.
```
